export const TYPES = {
    // Shorten
    SHORTEN_REQUEST: "SHORTEN_REQUEST",
    SHORTEN_REQUEST_SUCCESS: "SHORTEN_REQUEST_SUCCESS",
    SHORTEN_REQUEST_FAILTURE: "SHORTEN_REQUEST_FAILTURE",

    // Get
    GET_LINK_REQUEST: "GET_LINK_REQUEST",
    GET_LINK_REQUEST_SUCCESS: "GET_LINK_REQUEST_SUCCESS",
    GET_LINK_REQUEST_FAILTURE: "GET_LINK_REQUEST_FAILTURE",
};
